package factions.scenes;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.concurrent.atomic.AtomicInteger;

import com.googlecode.lanterna.TerminalSize;
import com.googlecode.lanterna.TextColor;
import com.googlecode.lanterna.bundle.LanternaThemes;
import com.googlecode.lanterna.gui2.BasicWindow;
import com.googlecode.lanterna.gui2.BorderLayout;
import com.googlecode.lanterna.gui2.Borders;
import com.googlecode.lanterna.gui2.Button;
import com.googlecode.lanterna.gui2.Component;
import com.googlecode.lanterna.gui2.Direction;
import com.googlecode.lanterna.gui2.EmptySpace;
import com.googlecode.lanterna.gui2.GridLayout;
import com.googlecode.lanterna.gui2.Label;
import com.googlecode.lanterna.gui2.LinearLayout;
import com.googlecode.lanterna.gui2.MultiWindowTextGUI;
import com.googlecode.lanterna.gui2.Panel;
import com.googlecode.lanterna.gui2.Separator;
import com.googlecode.lanterna.gui2.Window;
import com.googlecode.lanterna.screen.Screen;

import factions.Game;
import factions.IScene;
import factions.SceneManager;
import factions.characters.Guardian;
import factions.characters.Hunter;
import factions.characters.Wizard;

// Most code here was generated by Github Copilot with my supervision.
// note: most AIs are pretty dumb ngl
public class CharacterSelectionScene implements IScene {
    // I HATE that Java and C++ doesn't have proper encapsulated enums
    public static final int CHAR_GUARDIAN = 0;
    public static final int CHAR_WIZARD = 1;
    public static final int CHAR_HUNTER = 2;

    private static final String[] CHARACTER_NAMES = { "Guardian", "Wizard", "Hunter" };
    private static final String[][] CHARACTER_SPRITES = {
            {
                    "|`-._/\\_.-`|\n",
                    "|    ||    |\n",
                    "|___o()o___|\n",
                    "|__((<>))__|\n",
                    "\\   o\\/o   /\n",
                    " \\   ||   /\n",
                    "  \\  ||  /\n",
                    "   '.||.'\n",
                    "     ``",
            },
            {
                    "     *( )\n",
                    "    . //:\n",
                    "   * //\n",
                    "    // . *\n",
                    "   //\n",
                    "  //\n",
                    " //",
            },
            {
                    "    (\n",
                    "     \\\n",
                    "      )\n",
                    "##------->\n",
                    "      )\n",
                    "     /\n",
                    "    (",
            },
    };
    private static final TextColor[] CHARACTER_COLORS = {
            TextColor.ANSI.BLUE_BRIGHT,
            TextColor.ANSI.MAGENTA_BRIGHT,
            TextColor.ANSI.GREEN,
    };

    private static final String[] CHARACTER_DESCRIPTIONS = {
            "A stalwart defender with unbreakable armor.\nSpecializes in protecting allies and\nwithstanding heavy damage.",
            "A master of arcane arts with devastating\nspells. Fragile but extremely powerful\nwhen casting magic.",
            "A swift warrior who strikes with precision.\nBalanced stats with high critical hit\nchance and mobility."
    };

    private SceneManager _manager;
    private Screen _screen;

    private MultiWindowTextGUI _gui;
    private BasicWindow _window;
    private Label _fps_label;

    private int _selected_character;

    // NEW: Keep references to panels that need updating
    private Panel _preview_panel;
    private Panel _selector_panel;
    private Panel _center_panel;
    private AtomicInteger _current_selection;
    private Button[] _character_buttons;

    public CharacterSelectionScene(Screen screen) {
        _screen = screen;
        _selected_character = 0;
        _current_selection = new AtomicInteger(0);
        _character_buttons = new Button[CHARACTER_NAMES.length];
    }

    private Panel createSelectableCharacterCard(int idx, boolean selected) {
        Panel card = new Panel();
        card.setLayoutManager(new LinearLayout(Direction.VERTICAL));

        StringBuilder sprite_data = new StringBuilder();
        for (String sprite_line : CHARACTER_SPRITES[idx]) {
            sprite_data.append(sprite_line);
        }
        Label sprite = new Label(sprite_data.toString());
        sprite.setForegroundColor(selected ? TextColor.ANSI.YELLOW : CHARACTER_COLORS[idx]);
        sprite.setLayoutData(LinearLayout.createLayoutData(LinearLayout.Alignment.Center));
        card.addComponent(sprite);

        card.addComponent(new EmptySpace(new TerminalSize(0, 1)));

        Label name_label = new Label(CHARACTER_NAMES[idx]);
        name_label.setForegroundColor(
                selected ? TextColor.ANSI.YELLOW_BRIGHT : CHARACTER_COLORS[idx]);
        name_label.setLayoutData(
                LinearLayout.createLayoutData(LinearLayout.Alignment.Center));
        card.addComponent(name_label);

        if (selected) {
            card.addComponent(new EmptySpace(new TerminalSize(0, 1)));
            Label indicator = new Label("▼ SELECTED ▼");
            indicator.setForegroundColor(TextColor.ANSI.YELLOW_BRIGHT);
            indicator.setLayoutData(
                    LinearLayout.createLayoutData(LinearLayout.Alignment.Center));
            card.addComponent(indicator);
        }

        return card;
    }

    private void updatePreviewPanel(int index) {
        _preview_panel.removeAllComponents();

        Panel new_preview = createPreviewPanel(index);

        for (Component component : new_preview.getChildren()) {
            _preview_panel.addComponent(component);
        }
        _preview_panel.invalidate();
    }

    private void updateSelector(int index) {
        _selector_panel.removeAllComponents();

        // I don't know what happens here, but I will trust the IA this once
        for (int i = 0; i < CHARACTER_NAMES.length; i++) {
            final int char_index = i;
            Panel char_panel = createSelectableCharacterCard(i, index == i);

            Button char_button = new Button(CHARACTER_NAMES[i], () -> {
                _current_selection.set(char_index);
                updatePreviewPanel(char_index);
                updateSelector(char_index);

                if (_character_buttons[char_index] != null) {
                    _character_buttons[char_index].takeFocus();
                }
            });

            _character_buttons[char_index] = char_button;

            Panel wrapper = new Panel();
            wrapper.setLayoutManager(new LinearLayout(Direction.VERTICAL));

            wrapper.addComponent(char_panel);
            wrapper.addComponent(char_button.setLayoutData(
                    LinearLayout.createLayoutData(LinearLayout.Alignment.Center)));

            _selector_panel.addComponent(wrapper);
        }

        _selector_panel.invalidate();
    }

    private Panel createHorizontalSelector() {
        _selector_panel = new Panel();
        _selector_panel.setLayoutManager(new GridLayout(CHARACTER_NAMES.length));

        for (int i = 0; i < CHARACTER_NAMES.length; i++) {
            final int index = i;
            Panel char_panel = createSelectableCharacterCard(i, _current_selection.get() == i);

            Button char_button = new Button(CHARACTER_NAMES[i], () -> {
                _current_selection.set(index);
                updatePreviewPanel(index);
                updateSelector(index);

                if (_character_buttons[index] != null) {
                    _character_buttons[index].takeFocus();
                }
            });

            Panel wrapper = new Panel();
            wrapper.setLayoutManager(new LinearLayout(Direction.VERTICAL));

            wrapper.addComponent(char_panel);
            wrapper.addComponent(char_button.setLayoutData(
                    LinearLayout.createLayoutData(LinearLayout.Alignment.Center)));

            _selector_panel.addComponent(wrapper);
        }

        return _selector_panel;
    }

    private Panel createPreviewPanel(int idx) {
        Panel preview = new Panel();
        preview.setLayoutManager(new GridLayout(2));

        Panel left_panel = new Panel();
        left_panel.setLayoutManager(new LinearLayout(Direction.VERTICAL));

        Label name = new Label("=== " + CHARACTER_NAMES[idx] + " ===");
        name.setForegroundColor(CHARACTER_COLORS[idx]);
        name.setLayoutData(LinearLayout.createLayoutData(LinearLayout.Alignment.Center));

        left_panel.addComponent(name);// For Large Sprite + Name

        StringBuilder sprite_data = new StringBuilder();
        for (String sprite_line : CHARACTER_SPRITES[idx]) {
            sprite_data.append(sprite_line);
        }
        Label sprite = new Label(sprite_data.toString());
        sprite.setForegroundColor(CHARACTER_COLORS[idx]);
        sprite.setLayoutData(LinearLayout.createLayoutData(LinearLayout.Alignment.Center));
        left_panel.addComponent(sprite);

        Panel right_panel = new Panel(); // For Stats + Description
        right_panel.setLayoutManager(new LinearLayout(Direction.VERTICAL));

        Label stats_header = new Label("--- Stats ---");
        stats_header.setForegroundColor(TextColor.ANSI.CYAN);
        right_panel.addComponent(stats_header);

        ArrayList<String> stats = new ArrayList<>();
        switch (idx) {
            case CHAR_GUARDIAN: {
                stats.add(String.format("HP: %d", Guardian.BASE_PV));
                stats.add(String.format("ATK: %d", Guardian.BASE_ATK));
                stats.add(String.format("SPD: %.2f", Guardian.BASE_SPEED));
                break;
            }
            case CHAR_WIZARD: {
                stats.add(String.format("HP: %d", Wizard.BASE_PV));
                stats.add(String.format("ATK: %d", Wizard.BASE_ATK));
                stats.add(String.format("SPD: %.2f", Wizard.BASE_SPEED));
                break;
            }
            case CHAR_HUNTER: {
                stats.add(String.format("HP: %d", Hunter.BASE_PV));
                stats.add(String.format("ATK: %d", Hunter.BASE_ATK));
                stats.add(String.format("SPD: %.2f", Hunter.BASE_SPEED));
                break;
            }
        }

        for (String stat : stats) {
            Label stat_label = new Label("· " + stat);
            stat_label.setForegroundColor(new TextColor.RGB(200, 200, 200));
            right_panel.addComponent(stat_label);
        }

        Label desc_header = new Label("--- Description ---");
        desc_header.setForegroundColor(TextColor.ANSI.CYAN);
        right_panel.addComponent(desc_header);

        String[] desc_lines = CHARACTER_DESCRIPTIONS[idx].split("\n");
        for (String line : desc_lines) {
            Label desc_line = new Label(line);
            desc_line.setForegroundColor(new TextColor.RGB(180, 180, 180));
            right_panel.addComponent(desc_line);
        }

        preview.addComponent(left_panel);
        preview.addComponent(right_panel);
        return preview;
    }

    private Panel createSelectionPanel() {
        _center_panel = new Panel();
        _center_panel.setLayoutManager(new LinearLayout(Direction.VERTICAL));

        Panel title_panel = new Panel();
        Label title = new Label("⚔ Choose your fighter ⚔");
        title.setForegroundColor(TextColor.ANSI.CYAN);
        title_panel.addComponent(title);

        _center_panel.addComponent(title_panel
                .withBorder(Borders.doubleLine())
                .setLayoutData(LinearLayout.createLayoutData(LinearLayout.Alignment.Center)));

        _center_panel.addComponent(new EmptySpace(new TerminalSize(0, 1)));

        _preview_panel = createPreviewPanel(_current_selection.get());
        _center_panel.addComponent(_preview_panel
                .withBorder(Borders.doubleLine("Character Info")));

        _center_panel.addComponent(new EmptySpace(new TerminalSize(0, 1)));

        Panel selector_container = createHorizontalSelector();
        _center_panel.addComponent(selector_container
                .withBorder(Borders.singleLine("Select Character"))
                .setLayoutData(LinearLayout.createLayoutData(LinearLayout.Alignment.Center)));

        _center_panel.addComponent(new EmptySpace(new TerminalSize(0, 1)));

        // Action buttons
        Panel button_panel = new Panel();
        button_panel.setLayoutManager(new LinearLayout(Direction.HORIZONTAL));

        Button select_btn = new Button("[O] Confirm Selection", () -> {
            _selected_character = _current_selection.get();
            _manager.switchScene("battle");
        });

        Button back_btn = new Button("[X] Back to Menu", () -> {
            _manager.switchScene("main_menu");
        });

        button_panel.addComponent(select_btn);
        button_panel.addComponent(new EmptySpace(new TerminalSize(3, 0)));
        button_panel.addComponent(back_btn);
        button_panel.setLayoutData(LinearLayout.createLayoutData(LinearLayout.Alignment.Center));

        _center_panel.addComponent(button_panel);

        return _center_panel;
    }

    private Panel createFooter() {
        Panel footer = new Panel();
        footer.setLayoutManager(new LinearLayout(Direction.VERTICAL));

        footer.addComponent(new Separator(Direction.HORIZONTAL));

        Panel footer_content = new Panel();
        footer_content.setLayoutManager(new LinearLayout(Direction.HORIZONTAL));
        footer_content.setLayoutData(LinearLayout.createLayoutData(LinearLayout.Alignment.Center));

        Label controls = new Label("↑↓/TAB: Navigate | ENTER: Select Character | ESC: Back");
        controls.setForegroundColor(new TextColor.RGB(150, 150, 150));
        footer_content.addComponent(controls);

        footer_content.addComponent(new Separator(Direction.VERTICAL));

        _fps_label = new Label("FPS: 0");
        _fps_label.setForegroundColor(new TextColor.RGB(100, 100, 100));
        footer_content.addComponent(_fps_label);

        footer_content.addComponent(new EmptySpace(new TerminalSize(3, 1)));

        footer.addComponent(footer_content);
        return footer;
    }

    @Override
    public void update() {
        if (_fps_label != null) {
            _fps_label.setText("FPS: " + Game.getInstance().getCurrentFPS());
        }

        try {
            _gui.processInput();

            if (!_window.isVisible() || _gui.getWindows().isEmpty()) {
                if (_manager.getNextSceneName() == null)
                    _manager.switchScene("main_menu");
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    @Override
    public void render() throws IOException {
        _gui.updateScreen();
        _screen.refresh();
    }

    @Override
    public void onEnter() {
        _gui = new MultiWindowTextGUI(_screen);
        _gui.setTheme(LanternaThemes.getRegisteredTheme("darkone"));

        _window = new BasicWindow();
        _window.setHints(Arrays.asList(
                Window.Hint.FULL_SCREEN, Window.Hint.MODAL, Window.Hint.NO_DECORATIONS));

        Panel container = new Panel();
        container.setLayoutManager(new BorderLayout());

        container.addComponent(createSelectionPanel(), BorderLayout.Location.CENTER);
        container.addComponent(createFooter(), BorderLayout.Location.BOTTOM);

        _window.setComponent(container);
        _gui.addWindow(_window);
    }

    @Override
    public void onExit() {
        if (_window != null && _window.isVisible())
            _window.close();
    }

    @Override
    public void setSceneManager(SceneManager manager) {
        _manager = manager;
    }

    public int getSelectedCharacter() {
        return _selected_character;
    }
}
