package factions.scenes;

import java.io.IOException;
import java.util.Arrays;

import com.googlecode.lanterna.TerminalSize;
import com.googlecode.lanterna.TextColor;
import com.googlecode.lanterna.bundle.LanternaThemes;
import com.googlecode.lanterna.gui2.BasicWindow;
import com.googlecode.lanterna.gui2.BorderLayout;
import com.googlecode.lanterna.gui2.Button;
import com.googlecode.lanterna.gui2.Direction;
import com.googlecode.lanterna.gui2.EmptySpace;
import com.googlecode.lanterna.gui2.Label;
import com.googlecode.lanterna.gui2.LinearLayout;
import com.googlecode.lanterna.gui2.LinearLayout.Alignment;
import com.googlecode.lanterna.gui2.MultiWindowTextGUI;
import com.googlecode.lanterna.gui2.Panel;
import com.googlecode.lanterna.gui2.Separator;
import com.googlecode.lanterna.gui2.Window;
import com.googlecode.lanterna.screen.Screen;

import factions.Game;
import factions.IScene;
import factions.SceneManager;

// Most UI was generated by the Github Copilot
public class MainMenuScene implements IScene {
    private SceneManager _manager;
    private Screen _screen;

    private MultiWindowTextGUI _gui;
    private BasicWindow _window;
    private Label _fps_label;

    public MainMenuScene(Screen screen) {
        _screen = screen;
    }

    private Panel createMenu() {
        Panel main = new Panel();
        main.setLayoutManager(new LinearLayout(Direction.VERTICAL));

        String title = new String();
        title += "╔═════════════════════════╗\n";
        title += "║                         ║\n";
        title += "║   Factions Tournament   ║\n";
        title += "║                         ║\n";
        title += "╚═════════════════════════╝\n";
        Label title_label = new Label(title);
        title_label.setLayoutData(LinearLayout.createLayoutData(LinearLayout.Alignment.Center));
        main.addComponent(title_label);

        main.addComponent(new EmptySpace(new TerminalSize(0, 2)));

        // Buttons
        Button start_button = new Button("▶ Start Game", () -> {
            _manager.switchScene("character_select");
        });
        start_button.setLayoutData(LinearLayout.createLayoutData(LinearLayout.Alignment.Center));

        Button exit_button = new Button(" Exit", () -> {
            _manager.switchScene("exit", true);
        });
        exit_button.setLayoutData(LinearLayout.createLayoutData(LinearLayout.Alignment.Center));

        main.addComponent(start_button);
        main.addComponent(new EmptySpace(new TerminalSize(0, 1)));
        main.addComponent(exit_button);
        main.addComponent(new EmptySpace(new TerminalSize(0, 1)));

        return main;
    }

    private Panel createFooter() {
        Panel footer = new Panel();
        footer.setLayoutManager(new LinearLayout(Direction.VERTICAL));

        footer.addComponent(new Separator(Direction.HORIZONTAL));

        Panel footer_content = new Panel();
        footer_content.setLayoutManager(new LinearLayout(Direction.HORIZONTAL));
        footer_content.setLayoutData(LinearLayout.createLayoutData(LinearLayout.Alignment.Center));

        Label controls = new Label("↑↓/TAB Navigate | ENTER Select");
        controls.setForegroundColor(new TextColor.RGB(150, 150, 150));
        footer_content.addComponent(controls);

        footer_content.addComponent(new Separator(Direction.VERTICAL));

        _fps_label = new Label("FPS: 0");
        _fps_label.setForegroundColor(new TextColor.RGB(100, 100, 100));
        footer_content.addComponent(_fps_label);

        footer_content.addComponent(new EmptySpace(new TerminalSize(3, 1)));

        footer.addComponent(footer_content);
        return footer;
    }

    @Override
    public void update() {
        if (_fps_label != null) {
            _fps_label.setText("FPS: " + Game.getInstance().getCurrentFPS());
        }

        try {
            _gui.processInput();

            // Reset state if window is closed
            if (!_window.isVisible() || _gui.getWindows().isEmpty()) {
                if (_manager.getNextSceneName() == null)
                    _manager.switchScene("main_menu");
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    @Override
    public void render() throws IOException {
        _gui.updateScreen();
        _screen.refresh();
    }

    @Override
    public void onEnter() {
        _gui = new MultiWindowTextGUI(_screen);
        _gui.setTheme(LanternaThemes.getRegisteredTheme("darkone"));

        _window = new BasicWindow();
        _window.setHints(Arrays.asList(
                Window.Hint.FULL_SCREEN, Window.Hint.MODAL, Window.Hint.NO_DECORATIONS));

        Panel container = new Panel();
        container.setLayoutManager(new BorderLayout());

        container.addComponent(createMenu(), BorderLayout.Location.CENTER);
        container.addComponent(createFooter(), BorderLayout.Location.BOTTOM);

        _window.setComponent(container);
        _gui.addWindow(_window);
    }

    @Override
    public void onExit() {
        if (_window != null)
            _window.close();
    }

    @Override
    public void setSceneManager(SceneManager manager) {
        _manager = manager;
    }
}
